exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit, commit-msg]
fail_fast: false

repos:
  # own autoflake integration as the one from https://github.com/humitos/mirrors-autoflake does not work at all
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --in-place
        language: python
        additional_dependencies:
          - autoflake==1.4
        files: \.py$
        exclude: "migrations"
        args:
          [
            "--expand-star-imports",
          ]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff-format-check
        name: ruff-format-check
        args: [--check]
      - id: ruff-format
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        always_run: true
        args: [.git/COMMIT_EDITMSG]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
